# Header
menu:
	Home: /
	About Me: /aboutme/
	Github: https://github.com/stackOverMind
	#Open-Source: open-source/
	#Blog: blog/
	#Guestbook: guestbook/

# Profile
profile:
	location: Beijing, China
	github: stackovermind
	#stackoverflow: 
		#title: yumemor
		#href: http://stackoverflow.com/users/5662132/yumemor
	#organization: 组织/公司

#Widget
sidebar: true
navfixed: false

#WidgetText
excerpt_link: 继续阅读

#Github(请务必配置github帐号)
github:
  #popular_repos: ['ysale-sms','scude-answer','cordova-plugin-alipay']
  #contribute_repos: ['yumemor/fexo','yumemor/site']

#Comments
comments:
	#duoshuo_username: yumemor # 多说配置
	disqus_username: jack-x # disqus 配置

#Source Code
source_code: https://github.com/stackovermind/singularity
